### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by LampPrinter** [giovannicoppola/alfred-ticker#1]
![Screenshot 2022-02-20 at 7 17 50 AM Redacted](https://user-images.githubusercontent.com/7559328/154825265-e9df7a54-708f-42f1-af7a-ab76b1636e21.png)

Getting this.

**Comment by giovannicoppola** [comment]
is this resolved? It seems to work fine for me. If not, what are the tickers you are trying to fetch?

**Comment by LampPrinter** [comment]
Default AAPL,GOOG,TSLA.
Haven't changed anything expect entering API key.

Maybe something to do with python3.

I have just normally installed python3 by brew and have this in my .zshrc
"alias python=/opt/homebrew/bin/python3"

**Comment by giovannicoppola** [comment]
and you have python3 installed? 
never mind, I see you added that

I have this command to allow both homebrew and Xcode versions... perhaps you can try to remove that? 
`export PATH=/opt/homebrew/bin:/usr/local/bin:$PATH`

or call `python` instead of `python3`

**Comment by LampPrinter** [comment]
I am getting this now -
/lib/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

When I try to 'pip3 install urllib3'
I get 'Requirement already satisfied'

**Comment by LampPrinter** [comment]
It worked. Apparently I had to "Subscribe to Test" in the Yahoo API. Earlier I just copied the API key.

**Comment by giovannicoppola** [comment]
glad to hear. However you are correct that `urllib3` is nor bundled with `requests` as I thought. I will fix this.

**Comment by giovannicoppola** [comment]
I pushed a version that does not rely on `requests`. Thanks for your feedback!
